name: Deploy CDK Stacks

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
      CDK_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: | 
          npm install
          cd lambda
          npm install

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy Hosted Zone Stack
        run: |
          cdk synth HostedZoneStack
          cdk deploy --require-approval never HostedZoneStack

      - name: Deploy Frontend Stack
        run: |
          cdk synth FrontendStack
          cdk deploy --require-approval never FrontendStack

      - name: Deploy Dynamo Stack
        run: |
          cdk synth DynamoStack
          cdk deploy --require-approval never DynamoStack

      - name: Deploy Lambda Stack
        run: |
          cd lambda
          npm run build-all
          cd ..
          cdk synth LambdaStack
          cdk deploy --require-approval never LambdaStack
